name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Do a dry run to preview instead of a real release"
        required: true
        default: "true"

jobs:
  authorize:
    name: Authorize
    runs-on: macos-14
    steps:
      - name: ${{ github.actor }} permission check to do a release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/collaborators/${{ github.actor }}
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  release:
    name: Release
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout swift-create-xcframework
        uses: actions/checkout@v4
        with:
          repository: segment-integrations/swift-create-xcframework
          path: swift-create-xcframework
      - name: ls-1
        run: ls -la
      - name: ls-1
        run: ls -la swift-create-xcframework
      - name: Restore Build cache
        uses: actions/cache@v4
        with:
          path: swift-create-xcframework/.build
          key: $(git -C swift-create-xcframework rev-parse HEAD)

      - name: Build swift-create-xcframework
        run: make -C swift-create-xcframework swift-create-xcframework